### ISSUE TITLE
pls add 1.16.4 support

### ISSUE THREAD

**Issue by CloudeLecaw** [Andavin/Images#14]
```
[07:25:29] [Server thread/ERROR]: Could not load 'plugins\Images_2.1.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.4.jar:git-Paper-256]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.4.jar:git-Paper-256]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.4.jar:git-Paper-256]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.4.jar:git-Paper-256]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.4.jar:git-Paper-256]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.4.jar:git-Paper-256]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-256]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_231]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_231]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.4.jar:git-Paper-256]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.4.jar:git-Paper-256]
	... 7 more
Caused by: java.lang.UnsupportedOperationException: Class class com.andavin.images.PacketListener is not currently supported for version v1_16_R3
	at com.andavin.images.Versioned.getInstance(Versioned.java:60) ~[?:?]
	at com.andavin.images.Images.<clinit>(Images.java:100) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_231]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_231]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.4.jar:git-Paper-256]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.4.jar:git-Paper-256]
	... 7 more
```

**Comment by Blueeyestar** [comment]
Unfortunately we also have the problem :(

**Comment by CloudeLecaw** [comment]
thanks for updating <3
