### ISSUE TITLE
sun.awt.X11.XToolkit not found

### ISSUE THREAD

**Issue by Malfrador** [Andavin/Images#16]
Creating an image fails with the following error message:
```
java.lang.NoClassDefFoundError: Could not initialize class  
	at sun.awt.PlatformGraphicsInfo.createToolkit(PlatformGraphicsInfo.java:40) ~[?:?]
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:592) ~[?:?]
	at java.awt.Image.getScaledInstance(Image.java:178) ~[?:?]
	at com.andavin.images.command.CreateCommand$CreateImageTask.readImage(CreateCommand.java:260) ~[?:?]
```

- Purpur 1.16.4 (897)
- JDK 13 (not headless, so X11 should work fine)

**Comment by Andavin** [comment]
This is an issue with your Java installation. Unfortunately, I can't really do anything to help other than that.
