### ISSUE TITLE
Images does not work in the MC 1.17 version

### ISSUE THREAD

**Issue by Blueeyestar** [Andavin/Images#22]
Today the new MC version 1.17 came out. Unfortunately, as feared, the version number has to be adjusted again. It would be really great if this happened promptly, many users would be happy about that.

```
[09:10:23] [Server thread/ERROR]: Could not load 'plugins\Images_2.1.7.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:384) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:232) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	... 7 more
Caused by: java.lang.UnsupportedOperationException: Class class com.andavin.images.PacketListener is not currently supported for version v1_17_R1
	at com.andavin.images.Versioned.getInstance(Versioned.java:60) ~[?:?]
	at com.andavin.images.Images.<clinit>(Images.java:97) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[server.jar:3102-Spigot-c9cea60-4d2c780]
	... 7 more
```

**Comment by CloudeLecaw** [comment]
Im also hopen for an update for 1.17,

Our error on startup looks a bit simliar to the error Blueeyestar reported before,,

Here it is
```
[22:14:14] [Server thread/ERROR]: Could not load 'plugins\Images_2.1.7.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:384) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:232) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	... 7 more
Caused by: java.lang.UnsupportedOperationException: Class class com.andavin.images.PacketListener is not currently supported for version v1_17_R1
	at com.andavin.images.Versioned.getInstance(Versioned.java:60) ~[?:?]
	at com.andavin.images.Images.<clinit>(Images.java:97) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[server.jar:3124-Spigot-66f9d3c-384e116]
	... 7 more
```

**Comment by LoneDevilX** [comment]
Same issue having here https://pastebin.ubuntu.com/p/gKGsn9HHHG/

**Comment by 23Luzi23** [comment]
use images-2.2.1 from here https://translate.google.com/translate?hl=de&sl=en&u=https://www.spigotmc.org/resources/custom-images.53036/&prev=search&pto=aue

**Comment by 23Luzi23** [comment]
> Same issue having here https://pastebin.ubuntu.com/p/gKGsn9HHHG/

have you a image in a world named "void". Have you delete the world without delete the image?
