### ISSUE TITLE
Error on Worldchange and /spawn in 1.17.1

### ISSUE THREAD

**Issue by CloudeLecaw** [Andavin/Images#25]
```
[21:59:48] [Craft Scheduler Thread - 81/WARN]: [Images] Plugin Images v2.2.1 generated an exception while executing task 184542
java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int)'
	at com.andavin.images.v1_17_R1.MapHelper.destroyMap(MapHelper.java:114) ~[?:?]
	at com.andavin.images.MapHelper.destroyMaps(MapHelper.java:88) ~[?:?]
	at com.andavin.images.image.CustomImageSection.hide(CustomImageSection.java:153) ~[?:?]
	at com.andavin.images.image.CustomImage.refresh(CustomImage.java:180) ~[?:?]
	at com.andavin.images.Images.refreshImages(Images.java:437) ~[?:?]
	at com.andavin.images.Images.lambda$onMove$9(Images.java:256) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-88]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-88]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-88]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```
The error comes a vew times mostly-- maybe one for each pic in the world where the player was?

When the player enters the next world from worldchange then he see no pictues in the world after that error accoured.
To see them aggain he needs to relog
IPluginversion v2.2.1 

Edit: Now it happend with /spawn in same world too...

**Comment by CloudeLecaw** [comment]
oh i see the issue has been reported allready in
https://github.com/Andavin/Images/issues/24
