### ISSUE TITLE
plugin warning

### ISSUE THREAD

**Issue by myk3sr** [Andavin/Images#26]
console output

WARN01:18:40
[Images]: Plugin Images v2.2.1 generated an exception while executing task 4906
Console01:18:40
java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int)'
at com.andavin.images.v1_17_R1.MapHelper.destroyMap(MapHelper.java:114) ~[?:?]
at com.andavin.images.MapHelper.destroyMaps(MapHelper.java:88) ~[?:?]
at com.andavin.images.image.CustomImageSection.hide(CustomImageSection.java:153) ~[?:?]
at com.andavin.images.image.CustomImage.refresh(CustomImage.java:180) ~[?:?]
at com.andavin.images.Images.refreshImages(Images.java:437) ~[?:?]
at com.andavin.images.Images.lambda$onEnable$2(Images.java:172) ~[?:?]
at java.util.HashMap.forEach(HashMap.java:1425) ~[?:?]
at com.andavin.images.Images.lambda$onEnable$3(Images.java:166) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-103]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-103]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-103]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by MJRLegends** [comment]
Update to  Images v2.2.2

**Comment by MJRLegends** [comment]
https://www.spigotmc.org/resources/custom-images.53036/update?update=412991

**Comment by Andavin** [comment]
Assuming this is no longer an issue. Let me know if it is and I'll reopen the issue
