### ISSUE TITLE
Spigot 1.18.2

### ISSUE THREAD

**Issue by ErythroCraft** [Andavin/Images#38]
Hi

I would like updating my server to spigot 1.18.2
Your plugin could not load your plugin to the newest version of spigot.

Bugs:
The bugs are produced by loading the server with spigot Spigot v1_18_R2 .

java.lang.ExceptionInInitializerError

1. Caused by: java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]

2. java.lang.UnsupportedOperationException: Class class com.andavin.images.PacketListener is not currently supported for version v1_18_R2
        at com.andavin.images.Versioned.getInstance(Versioned.java:60) ~[?:?]
        at com.andavin.images.Images.<clinit>(Images.java:97) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]

**Comment by ErythroCraft** [comment]
Thanks for updating the plugin.
