### ISSUE TITLE
First sees issue on loading with Spigot 1.19

### ISSUE THREAD

**Issue by CloudeLecaw** [Andavin/Images#42]
```
[18:52:27] [Server thread/ERROR]: [31m[Minecraft] Could not load 'plugins\images_2.2.5.jar' in folder 'plugins'[0m
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:393) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:300) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:402) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:224) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:966) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ExceptionInInitializerError
	at com.andavin.images.Versioned.<clinit>(Versioned.java:42) ~[?:?]
	at com.andavin.images.Images.<clinit>(Images.java:97) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 7 more
Caused by: java.lang.UnsupportedOperationException: Version v1_19 is not supported.
	at com.andavin.util.MinecraftVersion.<clinit>(MinecraftVersion.java:158) ~[?:?]
	at com.andavin.images.Versioned.<clinit>(Versioned.java:42) ~[?:?]
	at com.andavin.images.Images.<clinit>(Images.java:97) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 7 more
Caused by: java.lang.IllegalArgumentException: No enum constant com.andavin.util.MinecraftVersion.v1_19
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at com.andavin.util.MinecraftVersion.valueOf(MinecraftVersion.java:60) ~[?:?]
	at com.andavin.util.MinecraftVersion.<clinit>(MinecraftVersion.java:156) ~[?:?]
	at com.andavin.images.Versioned.<clinit>(Versioned.java:42) ~[?:?]
	at com.andavin.images.Images.<clinit>(Images.java:97) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 7 more
```

**Comment by KeyboardKobold** [comment]
If you're able to build the code yourself maybe #43 will work for you.
