### ISSUE TITLE
Error on creation and Destrction of images

### ISSUE THREAD

**Issue by CloudeLecaw** [Andavin/Images#50]
```
[16:14:27 WARN]: [Images] Plugin Images v2.2.6 generated an exception while executing task 1326
java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(net.minecraft.network.chat.IChatBaseComponent, int)'
    at com.andavin.images.v1_19_R1.ActionBarUtil.sendMessage(ActionBarUtil.java:40) ~[Images_2.2.6.jar:?]
    at com.andavin.util.ActionBarUtil.sendActionBar(ActionBarUtil.java:45) ~[Images_2.2.6.jar:?]
    at com.andavin.images.command.DeleteCommand.lambda$execute$0(DeleteCommand.java:76) ~[Images_2.2.6.jar:?]
    at com.andavin.util.Scheduler$Task.run(Scheduler.java:353) ~[Images_2.2.6.jar:?]
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-125]
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-125]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

The Error is only shown once each time a  new picture is placed or destoryed in 1.19.2

**Comment by Andavin** [comment]
Fixed with the current version
