### ISSUE TITLE
Images v2.2.6 generates this error and spams it

### ISSUE THREAD

**Issue by danilacasito** [Andavin/Images#53]
`java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(net.minecraft.network.chat.IChatBaseComponent, int)'
        at com.andavin.images.v1_19_R1.ActionBarUtil.sendMessage(ActionBarUtil.java:40) ~[images-2.2.6.jar:?]
        at com.andavin.util.ActionBarUtil.sendActionBar(ActionBarUtil.java:45) ~[images-2.2.6.jar:?]
        at com.andavin.images.command.DeleteCommand.lambda$execute$0(DeleteCommand.java:76) ~[images-2.2.6.jar:?]
        at com.andavin.util.Scheduler$Task.run(Scheduler.java:353) ~[images-2.2.6.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-131]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-131]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Server: 1.19.2 PaperMC Build 131

**Comment by Andavin** [comment]
This is fixed as of version 2.2.7 with 1.19.2
