### ISSUE TITLE
probleme 

### ISSUE THREAD

**Issue by SkytraceXLSU** [Andavin/Images#55]
hey when i create new image i have an errror in console 

>.... [22:00:43 INFO]: skytraceX issued server command: /image create EventHallo.png 50
>....2022-10-15 22:00:46,023 Craft Scheduler Thread - 24 - Images ERROR Recursive call to appender Async
[22:00:46 WARN]: [Images] Plugin Images v2.2.7 generated an exception while executing task 3000
java.lang.NoSuchMethodError: 'net.minecraft.core.EnumDirection net.minecraft.world.entity.decoration.EntityItemFrame.cv()'
at com.andavin.images.v1_19_R1.MapHelper.createMap(MapHelper.java:104) ~[images-2.2.7.jar:?]
at com.andavin.images.MapHelper.createMap(MapHelper.java:77) ~[images-2.2.7.jar:?]
at com.andavin.images.image.CustomImageSection.show(CustomImageSection.java:141) ~[images-2.2.7.jar:?]
at com.andavin.images.image.CustomImage.refresh(CustomImage.java:175) ~[images-2.2.7.jar:?]
at com.andavin.images.command.CreateCommand.lambda$onInteract$5(CreateCommand.java:204) ~[images-2.2.7.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-65]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.jar:git-Paper-65]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

can you help me ?

**Comment by CloudeLecaw** [comment]
could you try version 2.2.6 
the 2.2.7 was made to support the 1.9.2 version...

here the update log of 2.2.7
```
mportant: This build is most likely only compatible with 1.19.2 and no longer 1.19.
All other versions of the game should be unaffected.

This build comes with a couple fixes for the major issues with the 1.19+ build:
Fixes when joining the server getting an invalid player move packet error
Fixes constructor not found from 1.19.2 when sending action bar messages

It's been a while since these bugs became an issue and since 1.19 came out so many of you may have...
```

**Comment by CloudeLecaw** [comment]
This thread has been closed due to prolonged inactivity. We assume the OP is no longer following this thread. If so, please create a new ticket. Thank you.
