### ISSUE TITLE
1.16.1 Spigot Errors

### ISSUE THREAD

**Issue by MJRLegends** [Andavin/Images#7]
```
[22:20:39] [Server thread/ERROR]: Could not load 'plugins/images-2.0.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[server.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[server.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[server.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:377) ~[server.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:186) ~[server.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:808) ~[server.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-758abbe-2b00831]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ExceptionInInitializerError
	at com.andavin.images.Versioned.<clinit>(Versioned.java:42) ~[?:?]
	at com.andavin.images.Images.<clinit>(Images.java:98) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_232]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-758abbe-2b00831]
	... 7 more
Caused by: java.lang.UnsupportedOperationException: Version v1_16 is not supported.
	at com.andavin.util.MinecraftVersion.<clinit>(MinecraftVersion.java:137) ~[?:?]
	at com.andavin.images.Versioned.<clinit>(Versioned.java:42) ~[?:?]
	at com.andavin.images.Images.<clinit>(Images.java:98) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_232]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-758abbe-2b00831]
	... 7 more
Caused by: java.lang.IllegalArgumentException: No enum constant com.andavin.util.MinecraftVersion.v1_16
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_232]
	at com.andavin.util.MinecraftVersion.valueOf(MinecraftVersion.java:60) ~[?:?]
	at com.andavin.util.MinecraftVersion.<clinit>(MinecraftVersion.java:135) ~[?:?]
	at com.andavin.images.Versioned.<clinit>(Versioned.java:42) ~[?:?]
	at com.andavin.images.Images.<clinit>(Images.java:98) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_232]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-758abbe-2b00831]
	... 7 more
```

**Comment by Blueeyestar** [comment]
I can confirm this problem

**Comment by Andavin** [comment]
Hi, this is not a problem or bug; the plugin simply does not support 1.16 as of yet.

**Comment by MJRLegends** [comment]
Yea understandable, was just to give you the error and notification that images plugin no long works on 1.16. :P
