### ISSUE TITLE
Plz update 2.3.2 in 1.20.6

### ISSUE THREAD

**Issue by DICEALPHAHU** [Andavin/Images#84]

**Comment by CloudeLecaw** [comment]
weare on 2.4.0 allready so pls update to 2.5.0 with 1.20.6 support 

```
[23:54:22] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'images_2.4.0.jar' in folder 'plugins\.paper-remapped'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:510) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
	at images_2.4.0.jar/com.andavin.images.Versioned.<clinit>(Versioned.java:42) ~[images_2.4.0.jar:?]
	at images_2.4.0.jar/com.andavin.images.Images.<clinit>(Images.java:97) ~[images_2.4.0.jar:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:529) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:508) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	... 9 more
Caused by: java.lang.StringIndexOutOfBoundsException: Range [23, -1) out of bounds for length 22
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[?:?]
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4914) ~[?:?]
	at java.base/java.lang.String.substring(String.java:2876) ~[?:?]
	at images_2.4.0.jar/com.andavin.util.MinecraftVersion.<clinit>(MinecraftVersion.java:168) ~[images_2.4.0.jar:?]
	at images_2.4.0.jar/com.andavin.images.Versioned.<clinit>(Versioned.java:42) ~[images_2.4.0.jar:?]
	at images_2.4.0.jar/com.andavin.images.Images.<clinit>(Images.java:97) ~[images_2.4.0.jar:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:529) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:508) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	... 9 more
```

**Comment by DICEALPHAHU** [comment]
errr.. where is it? not in Release and Spigot, plz build it in there ;)

**Comment by resi23** [comment]
I created this build temporarily: https://github.com/resi23/Images/releases/tag/v2.3.3

This is not an official build. Keep an eye on the [Spigot page](https://www.spigotmc.org/resources/custom-images.53036/) for an official update.

**Comment by DICEALPHAHU** [comment]
> I created this build temporarily: https://github.com/resi23/Images/releases/tag/v2.3.3 its Supports 1.20.5/6 Spigot and Paper Server
> 
> This is not an official build. Keep an eye on the [Spigot page](https://www.spigotmc.org/resources/custom-images.53036/) for an official update.

it worked so appreciate

**Comment by CloudeLecaw** [comment]
i agree 2.3.3 worked for us for 1.20.6 paper

**Comment by CloudeLecaw** [comment]
2.4.0 never was an einem official verwion the dev jist posted it in an thread as file extansions while other thought is a releaee

**Comment by CloudeLecaw** [comment]
> 
![Screenshot_2024-05-31-12-34-20-634_com android chrome-edit](https://github.com/Andavin/Images/assets/12080017/3cbaa6c6-535f-4b1c-9307-3c20c4d5b477)

**Comment by CloudeLecaw** [comment]
This ticket was closed because it should be solved.
Let me know if its still appears with
https://github.com/resi23/Images/releases/tag/v2.3.3
then we can reopen ore make a new ticket
