### ISSUE TITLE
Minecraft 1.16.2 incompatible

### ISSUE THREAD

**Issue by Blueeyestar** [Andavin/Images#9]
A new MC version is out now, 1.16.2, and so the fun starts all over again for all server owners. I hereby post the first mistake. Welcome to sleep

`[01:43:02] [Server thread/ERROR]: Could not load 'plugins\images-2.1.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[server.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[server.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[server.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:381) ~[server.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:186) ~[server.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[server.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-379750e-43c7ff9]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_231]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_231]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-379750e-43c7ff9]
	... 7 more
Caused by: java.lang.UnsupportedOperationException: Class class com.andavin.images.PacketListener is not currently supported for version v1_16_R2
	at com.andavin.images.Versioned.getInstance(Versioned.java:60) ~[?:?]
	at com.andavin.images.Images.<clinit>(Images.java:100) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_231]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_231]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-379750e-43c7ff9]
	... 7 more`

https://pastebin.com/dmSw85WT

**Comment by Andavin** [comment]
Solved
