### ISSUE TITLE
imagesSpigot Version 2.4.0 has confilics on loading with new 1.20.6 paper

### ISSUE THREAD

**Issue by CloudeLecaw** [Andavin/Images#90]
```
[11:20:13] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'images_2.4.0.jar' in folder 'plugins\.paper-remapped'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:129) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:510) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
	at images_2.4.0.jar/com.andavin.images.Versioned.<clinit>(Versioned.java:42) ~[images_2.4.0.jar:?]
	at images_2.4.0.jar/com.andavin.images.Images.<clinit>(Images.java:97) ~[images_2.4.0.jar:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:529) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:508) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	... 9 more
Caused by: java.lang.StringIndexOutOfBoundsException: Range [23, -1) out of bounds for length 22
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[?:?]
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4914) ~[?:?]
	at java.base/java.lang.String.substring(String.java:2876) ~[?:?]
	at images_2.4.0.jar/com.andavin.util.MinecraftVersion.<clinit>(MinecraftVersion.java:168) ~[images_2.4.0.jar:?]
	at images_2.4.0.jar/com.andavin.images.Versioned.<clinit>(Versioned.java:42) ~[images_2.4.0.jar:?]
	at images_2.4.0.jar/com.andavin.images.Images.<clinit>(Images.java:97) ~[images_2.4.0.jar:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:529) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:508) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	... 9 more
```

**Comment by CloudeLecaw** [comment]
Just for info
The unoffical version vom Resi123 is loading and works on 1.20.6... 

https://github.com/resi23/Images/releases/tag/v2.3.3  this one

**Comment by resi23** [comment]
https://github.com/resi23/Images/releases/tag/v2.3.4

work on Spigot 1.20.5/6 and 1.21

**Comment by resi23** [comment]
Version 2.3.4-PaperFix works now with 1.21 Spigot AND Paper
https://github.com/resi23/Images/releases/tag/v2.3.4-PaperFix

**Comment by CloudeLecaw** [comment]
closed because it was updated
