### ISSUE TITLE
We need an update for Spigot/Paper 1.21.1 :3

### ISSUE THREAD

**Issue by CloudeLecaw** [Andavin/Images#97]
```
[18:47:19] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'images_2.3.4-PaperFix.jar' in folder 'plugins/.paper-remapped'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:129) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
	at images_2.3.4-PaperFix.jar/com.andavin.util.MinecraftVersion.<clinit>(MinecraftVersion.java:224) ~[images_2.3.4-PaperFix.jar:?]
	at images_2.3.4-PaperFix.jar/com.andavin.images.Versioned.<clinit>(Versioned.java:42) ~[images_2.3.4-PaperFix.jar:?]
	at images_2.3.4-PaperFix.jar/com.andavin.images.Images.<clinit>(Images.java:97) ~[images_2.3.4-PaperFix.jar:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
	... 9 more
Caused by: java.lang.UnsupportedOperationException: Minor version 1.21.1 is not supported.
	at images_2.3.4-PaperFix.jar/com.andavin.util.MinecraftVersion$MinorVersion.<clinit>(MinecraftVersion.java:419) ~[images_2.3.4-PaperFix.jar:?]
	at images_2.3.4-PaperFix.jar/com.andavin.util.MinecraftVersion.<clinit>(MinecraftVersion.java:224) ~[images_2.3.4-PaperFix.jar:?]
	at images_2.3.4-PaperFix.jar/com.andavin.images.Versioned.<clinit>(Versioned.java:42) ~[images_2.3.4-PaperFix.jar:?]
	at images_2.3.4-PaperFix.jar/com.andavin.images.Images.<clinit>(Images.java:97) ~[images_2.3.4-PaperFix.jar:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
	... 9 more
Caused by: java.lang.IllegalArgumentException: No enum constant com.andavin.util.MinecraftVersion.MinorVersion.1.21.1
	at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
	at images_2.3.4-PaperFix.jar/com.andavin.util.MinecraftVersion$MinorVersion.valueOf(MinecraftVersion.java:343) ~[images_2.3.4-PaperFix.jar:?]
	at images_2.3.4-PaperFix.jar/com.andavin.util.MinecraftVersion$MinorVersion.<clinit>(MinecraftVersion.java:417) ~[images_2.3.4-PaperFix.jar:?]
	at images_2.3.4-PaperFix.jar/com.andavin.util.MinecraftVersion.<clinit>(MinecraftVersion.java:224) ~[images_2.3.4-PaperFix.jar:?]
	at images_2.3.4-PaperFix.jar/com.andavin.images.Versioned.<clinit>(Versioned.java:42) ~[images_2.3.4-PaperFix.jar:?]
	at images_2.3.4-PaperFix.jar/com.andavin.images.Images.<clinit>(Images.java:97) ~[images_2.3.4-PaperFix.jar:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
	... 9 more
```

**Comment by resi23** [comment]
There is now 2.5.0 from the official site but it is not yet compatible with 1.20.1

**Comment by resi23** [comment]
Try https://github.com/resi23/Images/releases/tag/v2.5.0

**Comment by Rexi666** [comment]
i had the same error, but that fix is working

**Comment by CloudeLecaw** [comment]
> i had the same error, but that fix is working

Well we use the 2.5 on our server paper 1.21.1 and it works...

**Comment by resi23** [comment]
Offical 2.5.1 with 1.21.1 Support is out. can close

**Comment by CloudeLecaw** [comment]
closed because it was updated
